"""init_db

Revision ID: 57710d3bdf73
Revises: 
Create Date: 2026-08-04 11:24:21.187001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57710d3bdf73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('CS', 'SALES', 'DOCTOR', name='knowledge_domain'), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'CS_GAP', 'SALES_CASE', name='knowledge_source_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', name='knowledge_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('cs_gap_id', sa.Integer(), nullable=True),
    sa.Column('sales_case_id', sa.Integer(), nullable=True),
    sa.Column('vector_doc_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_knowledge_items_id'), 'core_knowledge_items', ['id'], unique=False)
    op.create_table('core_sales_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.String(length=128), nullable=False),
    sa.Column('raw_chat_log', sa.Text(), nullable=False),
    sa.Column('customer_type', sa.String(length=255), nullable=True),
    sa.Column('core_objection', sa.Text(), nullable=True),
    sa.Column('breakthrough_logic', sa.Text(), nullable=True),
    sa.Column('follow_up_script', sa.Text(), nullable=True),
    sa.Column('extracted_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='sales_case_status'), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['core_knowledge_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_sales_cases_id'), 'core_sales_cases', ['id'], unique=False)
    op.create_table('core_unanswered_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PROCESSING', 'RESOLVED', 'IGNORED', name='unanswered_status'), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['core_knowledge_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_unanswered_questions_id'), 'core_unanswered_questions', ['id'], unique=False)
    op.create_table('cs_chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WXKF', 'MP', 'H5', 'WECOM_GROUP', name='chat_channel'), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('open_id', sa.String(length=128), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('retrieved_chunks', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('satisfaction', sa.SmallInteger(), nullable=True),
    sa.Column('hit_human', sa.Boolean(), nullable=False),
    sa.Column('human_takeover', sa.String(length=128), nullable=True),
    sa.Column('risk_flag', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_chat_logs_created_at'), 'cs_chat_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_cs_chat_logs_id'), 'cs_chat_logs', ['id'], unique=False)
    op.create_index(op.f('ix_cs_chat_logs_open_id'), 'cs_chat_logs', ['open_id'], unique=False)
    op.create_index(op.f('ix_cs_chat_logs_session_id'), 'cs_chat_logs', ['session_id'], unique=False)
    op.create_table('cs_leads_preview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('open_id', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.Enum('WXKF', 'MP', 'H5', 'WECOM_GROUP', name='chat_channel'), nullable=False),
    sa.Column('intent_tags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'CONVERTED', 'CLOSED', name='lead_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_leads_preview_created_at'), 'cs_leads_preview', ['created_at'], unique=False)
    op.create_index(op.f('ix_cs_leads_preview_id'), 'cs_leads_preview', ['id'], unique=False)
    op.create_index(op.f('ix_cs_leads_preview_open_id'), 'cs_leads_preview', ['open_id'], unique=False)
    op.create_table('cs_session_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.Enum('WXKF', 'MP', 'H5', 'WECOM_GROUP', name='chat_channel'), nullable=False),
    sa.Column('open_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('NORMAL', 'HUMAN_MODE', 'BLOCKED', name='session_state_value'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('negative_streak', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_session_state_id'), 'cs_session_state', ['id'], unique=False)
    op.create_index(op.f('ix_cs_session_state_open_id'), 'cs_session_state', ['open_id'], unique=False)
    op.create_index(op.f('ix_cs_session_state_session_id'), 'cs_session_state', ['session_id'], unique=True)
    # core 领域内部循环外键：knowledge_items <-> unanswered_questions / sales_cases，
    # 必须等被引用表创建后再追加（MySQL 不允许建表时引用尚未存在的表）
    op.create_foreign_key(
        'fk_core_knowledge_items_cs_gap_id',
        'core_knowledge_items', 'core_unanswered_questions',
        ['cs_gap_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_core_knowledge_items_sales_case_id',
        'core_knowledge_items', 'core_sales_cases',
        ['sales_case_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cs_session_state_session_id'), table_name='cs_session_state')
    op.drop_index(op.f('ix_cs_session_state_open_id'), table_name='cs_session_state')
    op.drop_index(op.f('ix_cs_session_state_id'), table_name='cs_session_state')
    op.drop_table('cs_session_state')
    op.drop_index(op.f('ix_cs_leads_preview_open_id'), table_name='cs_leads_preview')
    op.drop_index(op.f('ix_cs_leads_preview_id'), table_name='cs_leads_preview')
    op.drop_index(op.f('ix_cs_leads_preview_created_at'), table_name='cs_leads_preview')
    op.drop_table('cs_leads_preview')
    op.drop_index(op.f('ix_cs_chat_logs_session_id'), table_name='cs_chat_logs')
    op.drop_index(op.f('ix_cs_chat_logs_open_id'), table_name='cs_chat_logs')
    op.drop_index(op.f('ix_cs_chat_logs_id'), table_name='cs_chat_logs')
    op.drop_index(op.f('ix_cs_chat_logs_created_at'), table_name='cs_chat_logs')
    op.drop_table('cs_chat_logs')
    op.drop_index(op.f('ix_core_unanswered_questions_id'), table_name='core_unanswered_questions')
    op.drop_table('core_unanswered_questions')
    op.drop_index(op.f('ix_core_sales_cases_id'), table_name='core_sales_cases')
    op.drop_table('core_sales_cases')
    op.drop_index(op.f('ix_core_knowledge_items_id'), table_name='core_knowledge_items')
    op.drop_constraint('fk_core_knowledge_items_sales_case_id', 'core_knowledge_items', type_='foreignkey')
    op.drop_constraint('fk_core_knowledge_items_cs_gap_id', 'core_knowledge_items', type_='foreignkey')
    op.drop_table('core_knowledge_items')
    # ### end Alembic commands ###
