"""add_category_to_core_knowledge_items

Revision ID: 6073b7f19ee8
Revises: 57710d3bdf73
Create Date: 2026-08-04 13:16:55.403466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6073b7f19ee8'
down_revision: Union[str, Sequence[str], None] = '57710d3bdf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 原生 SQL 以支持 AFTER status（op.add_column 不支持 existing_* 参数）
    op.execute(
        "ALTER TABLE core_knowledge_items "
        "ADD COLUMN category VARCHAR(64) NOT NULL DEFAULT 'GENERAL' AFTER status"
    )
    op.create_index(op.f('ix_core_knowledge_items_category'), 'core_knowledge_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_knowledge_items_category'), table_name='core_knowledge_items')
    op.execute("ALTER TABLE core_knowledge_items DROP COLUMN category")
    # ### end Alembic commands ###
